FROM debian:bookworm-slim

RUN apt-get update && apt-get upgrade -y \
    && apt-get -y --no-install-recommends install wget ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY bibertest.sh /root

#ENTRYPOINT [ "/root/bibertest.sh" ]
#CMD ["dev", "plk/biber"]
CMD [ "/root/bibertest.sh" ]

