FROM debian:bookworm-slim

RUN apt-get update && apt-get upgrade -y \
    && apt-get -y --no-install-recommends install wget=1.21.3-1+b1 ca-certificates=20230311 \
    && rm -rf /var/lib/apt/lists/*

COPY bibertest.sh /

ENTRYPOINT [ "./bibertest.sh" ]
CMD ["dev", "plk/biber"]
