FROM perl:5.40.5-bookworm

RUN apt-get update && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y libbtparse-dev \
    && apt clean \
    && apt autoremove --purge && apt clean && rm -rf /var/lib/apt/lists/*

ENV PERL_CPANM_OPT="--verbose --mirror https://www.cpan.org --notest"
ENV PERL_TEST_POD=1

RUN cpanm CPAN \
&& cpanm Test::Regexp \
&& cpanm Test::Pod \
&& cpanm inc::latest \
&& cpanm Archive::Zip \
&& cpanm Net::SSLeay \
&& cpanm IO::Socket::SSL \
&& cpanm LWP::Protocol::https \
&& cpanm Business::ISBN \
&& cpanm Business::ISMN \
&& cpanm Business::ISSN \
&& cpanm Class::Accessor \
&& cpanm Data::Compare \
&& cpanm Data::Dump \
&& cpanm Data::Uniqid \
&& cpanm Dist::CheckConflicts \
&& cpanm Module::Runtime \
&& cpanm DateTime::Calendar::Julian \
&& cpanm DateTime::Format::Builder \
&& cpanm Encode::EUCJPASCII \
&& cpanm Encode::HanExtra \
&& cpanm Encode::JIS2K \
&& cpanm File::Slurper \
&& cpanm IPC::Run3 \
&& cpanm Lingua::Translit \
&& cpanm List::AllUtils \
&& cpanm List::MoreUtils \
&& cpanm List::MoreUtils::XS \
&& cpanm Log::Log4perl \
&& cpanm PerlIO::utf8_strict \
&& cpanm Parse::RecDescent \
&& cpanm Regexp::Common \
&& cpanm Sort::Key \
&& cpanm Text::BibTeX \
&& cpanm Text::CSV \
&& cpanm Text::CSV_XS \
&& cpanm Text::Roman \
# Force installation of Unicode::* modules (as they already exist as core modules).
&& cpanm --force Unicode::Collate::Locale \
&& cpanm --force Unicode::Collate \
&& cpanm --force Unicode::GCString \
&& cpanm --force Unicode::LineBreak \
&& cpanm XML::LibXML \
&& cpanm XML::LibXML::Simple \
&& cpanm XML::LibXSLT \
&& cpanm XML::Writer \
&& cpanm autovivification \
&& cpanm Config::AutoConf \
&& cpanm ExtUtils::LibBuilder \
&& cpanm File::Which \
&& cpanm Test::Differences \
&& cpanm IO::String \
&& cpanm Unicode::Normalize \
&& cpanm Getopt::ArgvFile \
&& cpanm Module::ScanDeps \
&& cpanm Specio::XS \
&& cpanm Specio::PP \
&& cpanm PAR \
&& cpanm PAR::Dist \
&& perl -MCPAN -e 'my $c = "CPAN::HandleConfig"; $c->load(doit => 1, autoconfig => 1); $c->edit(recommends_policy => "0"); $c->commit' \
&& cpanm PAR::Packer \
&& cpan  Module::Build \
&& cpan -f Unicode::Collate::Locale

# https://docs.docker.com/engine/reference/builder/#copy---link
# COPY --link biberbuild.sh /
COPY biberbuild.sh /root

WORKDIR /root

# https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example
ENTRYPOINT ["./biberbuild.sh"]
# BIBER_BRANCH and BIBER_REPO
CMD ["dev", "plk/biber"]
